GET  http://localhost:8080/login/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiMUBhZ2VuY2lhLmNvbSIsInNlbmhhIjoic2VuaGEifSwiaWF0IjoxNjg4NDEzNjczLCJleHAiOjE2ODg0MTQyNzN9.K005peo0TnGRL082ehWZ20h_t_jrA_FWzRoJymzczzE