GET  http://localhost:8080/login/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImVtYWlsIjoiMUBhZ2VuY2lhLmNvbSIsInNlbmhhIjoic2VuaGEifSwiaWF0IjoxNjg3MTgxMjYxLCJleHAiOjE2ODcxODEzMjF9.qI7_lGimkRCZIcCcrkbQBtxLapkYC8tD3Yjsu7MRP0g